### ISSUE TITLE
attempt to index global 'RAV_data' (a nil value)

### ISSUE THREAD

**Issue by Ookami313** [RavenousAddons/SecretFish#2]
## Expected behaviour
No error.

## Actual behaviour
Error occurring after updating to 1.3.3 and logging into the game. Thanks.

## Steps to reproduce this behaviour

1x SecretFish/functions.lua:51: attempt to index global 'RAV_data' (a nil value)
[string "@SecretFish/functions.lua"]:51: in function <SecretFish/functions.lua:50>
[string "@SecretFish/functions.lua"]:93: in function `SetDefaultSettings'
[string "@SecretFish/core.lua"]:16: in function <SecretFish/core.lua:14>

Locals:
key = "windowWidth"
value = 420
(*temporary) = nil
(*temporary) = "attempt to index global 'RAV_data' (a nil value)"

@waldenp0nd

**Comment by waldenp0nd** [comment]
Hey @Ookami313,

Thanks for this bug report. Huge oversight on my part, apologies.

Fixed with 8516b61, now published in version 1.3.4 .
